// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-NxKnXzNPR0co7esjdP_ABQc-a86CYEQ',
    appId: '1:105576756227:web:285afe70a961d344408a36',
    messagingSenderId: '105576756227',
    projectId: 'taskolasapp',
    authDomain: 'taskolasapp.firebaseapp.com',
    storageBucket: 'taskolasapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAtQ3iIJHfo_itN2C_kKjgX6Dk_V6x1vE',
    appId: '1:105576756227:android:e979288f0e58d159408a36',
    messagingSenderId: '105576756227',
    projectId: 'taskolasapp',
    storageBucket: 'taskolasapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-QO5K4XyVq8qm8ebg6QCMtM7KUrPXjTU',
    appId: '1:105576756227:ios:69018b07dbd6fa8e408a36',
    messagingSenderId: '105576756227',
    projectId: 'taskolasapp',
    storageBucket: 'taskolasapp.appspot.com',
    iosBundleId: 'com.example.taskolas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-QO5K4XyVq8qm8ebg6QCMtM7KUrPXjTU',
    appId: '1:105576756227:ios:7c05e3f79885ed6b408a36',
    messagingSenderId: '105576756227',
    projectId: 'taskolasapp',
    storageBucket: 'taskolasapp.appspot.com',
    iosBundleId: 'com.example.taskolas.RunnerTests',
  );
}
